Blogger/ViewComponents/MenulerViewComponent.cs
using Blogger.Models;
using Microsoft.AspNetCore.Mvc;

namespace Blogger.ViewComponents
{
    public class MenulerViewComponent:ViewComponent
    {
        private DatabaseContext db;
        public MenulerViewComponent(DatabaseContext db) 
        {
            this.db = db;
        }
        public IViewComponentResult Invoke()
        {
            return View(db.Pages.ToList());
        }
    }
}

Blogger/Views/_Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Eterna - Professional bootstrap site template for corporate business</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- css -->
    <link href="https://fonts.googleapis.com/css?family=Handlee|Open+Sans:300,400,600,700,800" rel="stylesheet">

    <link href="/css/bootstrap.css" rel="stylesheet" />

    <link href="/css/bootstrap-responsive.css" rel="stylesheet" />

    <link href="/css/flexslider.css" rel="stylesheet" />
    <link href="/css/prettyPhoto.css" rel="stylesheet" />
    <link href="/css/camera.css" rel="stylesheet" />
    <link href="/css/jquery.bxslider.css" rel="stylesheet" />
    <link href="/css/style.css" rel="stylesheet" />

    <!-- Theme skin -->
    <link href="/color/default.css" rel="stylesheet" />
</head>
<body>
    <div id="wrapper">
        <header>
            <div class="top">
                <div class="container">
                    <div class="row">
                        <div class="span6">
                            <p class="topcontact"><i class="icon-phone"></i> +62 088 999 123</p>
                        </div>
                        <div class="span6">

                            <ul class="social-network">
                                <li><a href="#" data-placement="bottom" title="Facebook"><i class="icon-facebook icon-white"></i></a></li>
                                <li><a href="#" data-placement="bottom" title="Twitter"><i class="icon-twitter icon-white"></i></a></li>
                                <li><a href="#" data-placement="bottom" title="Linkedin"><i class="icon-linkedin icon-white"></i></a></li>
                                <li><a href="#" data-placement="bottom" title="Pinterest"><i class="icon-pinterest  icon-white"></i></a></li>
                                <li><a href="#" data-placement="bottom" title="Google +"><i class="icon-google-plus icon-white"></i></a></li>
                                <li><a href="#" data-placement="bottom" title="Dribbble"><i class="icon-dribbble icon-white"></i></a></li>
                            </ul>

                        </div>
                    </div>
                </div>
            </div>
            <div class="container">

                <div class="row nomargin">
                    <div class="span4">
                        <div class="logo">
                            <a href=""><img src="/img/logo.png" alt="" /></a>
                        </div>
                    </div>
                    <div class="span8">
                        <div class="navbar navbar-static-top">
                            <div class="navigation">
                                <nav>
                                    <ul class="nav topnav">
                                        <li>
                                            <a href="/"><i class="icon-home"></i> Anasayfa </a>
                                        </li>
                                        @await Component.InvokeAsync("Menuler")
                                        <li class="dropdown">
                                            <a href="/projects">Projelerim</a>
                                        </li>
                                        <li class="dropdown">
                                            <a href="/bloglar">Bloglarım</a>
                                        <li>
                                            <a href="/iletisim">İletişim </a>
                                        </li>
                                    </ul>
                                </nav>
                            </div>
                            <!-- end navigation -->
                        </div>
                    </div>
                </div>
            </div>
        </header>

        @RenderBody()

        <footer>
            <div class="container">
                <div class="row">
                    <div class="span4">
                        <div class="widget">
                            <h5 class="widgetheading">Browse pages</h5>
                            <ul class="link-list">
                                <li><a href="#">Our company</a></li>
                                <li><a href="#">Terms and conditions</a></li>
                                <li><a href="#">Privacy policy</a></li>
                                <li><a href="#">Press release</a></li>
                                <li><a href="#">What we have done</a></li>
                                <li><a href="#">Our support forum</a></li>
                            </ul>

                        </div>
                    </div>
                    <div class="span4">
                        <div class="widget">
                            <h5 class="widgetheading">Get in touch</h5>
                            <address>
                                <strong>Eterna company Inc.</strong><br>
                                Somestreet 200 VW, Suite Village A.001<br>
                                Jakarta 13426 Indonesia
                            </address>
                            <p>
                                <i class="icon-phone"></i> (123) 456-7890 - (123) 555-7891 <br>
                                <i class="icon-envelope-alt"></i> email@domainname.com
                            </p>
                        </div>
                    </div>
                    <div class="span4">
                        <div class="widget">
                            <h5 class="widgetheading">Subscribe newsletter</h5>
                            <p>
                                Keep updated for new releases and freebies. Enter your e-mail and subscribe to our newsletter.
                            </p>
                            <form class="subscribe">
                                <div class="input-append">
                                    <input class="span2" id="appendedInputButton" type="text">
                                    <button class="btn btn-theme" type="submit">Subscribe</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div id="sub-footer">
                <div class="container">
                    <div class="row">
                        <div class="span6">
                            <div class="copyright">
                                <p><span>&copy; Eterna company. All right reserved</span></p>
                            </div>

                        </div>

                        <div class="span6">
                            <div class="credits">
                                <!--
                                  All the links in the footer should remain intact.
                                  You can delete the links only if you purchased the pro version.
                                  Licensing information: https://bootstrapmade.com/license/
                                  Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=Eterna
                                -->
                                Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
    </div>

    <!-- javascript
      ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="/js/jquery.js"></script>
    <script src="/js/jquery.easing.1.3.js"></script>
    <script src="/js/bootstrap.js"></script>

    <script src="/js/modernizr.custom.js"></script>
    <script src="/js/toucheffects.js"></script>
    <script src="/js/google-code-prettify/prettify.js"></script>
    <script src="/js/jquery.bxslider.min.js"></script>
    <script src="/js/camera/camera.js"></script>
    <script src="/js/camera/setting.js"></script>

    <script src="/js/jquery.prettyPhoto.js"></script>
    <script src="/js/portfolio/jquery.quicksand.js"></script>
    <script src="/js/portfolio/setting.js"></script>

    <script src="/js/jquery.flexslider.js"></script>
    <script src="/js/animate.js"></script>
    <script src="/js/inview.js"></script>

    <!-- Template Custom JavaScript File -->
    <script src="/js/custom.js"></script>



</body>

</html>